### ISSUE TITLE
Please update it to the latest ccminer version

### ISSUE THREAD

**Issue by elementarvodka1** [Mr-Bossman/CCminer-IOS#3]
I was using the app for a long time but since 1-2 months the old ccminer version is not compatible with their current algorithm. So please recompile it, i sadly dont know how to do it. thankss :3

**Comment by Mr-Bossman** [comment]
@elementarvodka1 This is in the works. I no longer have a Mac to compile it on and am working on getting one. I should have a release by the end of next month. If not, I forgot, and I need to be reminded.

**Comment by elementarvodka1** [comment]
Hey. I got a mac here which can run High Sierra to Catalina. Also there are VMs to run Mac under Windows in Vmware or Virtualbox. If you somehow could give me detailed instructions what exactly i have to do i could try doing it myself and you wont get a mac for that if i can do it on my own, I dont wanna cause any trouble for you but like 80-100  MH/s were in my iPhones and yes, i got a lot of them jailbroken and setup for mining. Thank you so much for your answer,

**Comment by Mr-Bossman** [comment]
It's not simple instructions I can give you, I honestly wish I was that simple. Like I said, I will get to it by the end of this month. I'm currently quite busy. You should be able to follow the general overview in the Readme on how to compile it. The repo it talks about is this
https://github.com/Mr-Bossman/ccminer/tree/IOS

**Comment by Mr-Bossman** [comment]
@elementarvodka1 please test https://github.com/Mr-Bossman/CCminer-IOS/releases/tag/pre4

**Comment by elementarvodka1** [comment]
@Mr-Bossman Thank you so much for compiling a new version - but as i said in the discord server, IOS 16 is way way way too high. I wanna run the miner on IPhone 5s to 7 Devices which run anything from IOS 12-15 so it has to work on these versions. Many of the other people would wanna run it on these older devices too because getting the newer ones is not profitable.

**Comment by Mr-Bossman** [comment]
@elementarvodka1 please test again
